# Generated by Django 5.1.7 on 2025-04-15 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('High Intensity', 'High Intensity'), ('Low Intensity', 'Low Intensity'), ('Weight Lifting', 'Weight Lifting'), ('Calisthenics', 'Calisthenics')], max_length=50)),
                ('intensity', models.CharField(choices=[('Weight Loss', 'Weight Loss'), ('Muscle Gain', 'Muscle Gain'), ('General Fitness', 'General Fitness')], max_length=50)),
                ('muscle_group', models.CharField(choices=[('Full Body', 'Full Body'), ('Legs', 'Legs'), ('Chest', 'Chest'), ('Back', 'Back'), ('Arms', 'Arms'), ('Shoulders', 'Shoulders'), ('Core', 'Core')], max_length=50)),
                ('description', models.TextField()),
                ('instruction', models.IntegerField(help_text='Duration in minutes')),
                ('image_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
