# Generated by Django 5.1.7 on 2025-05-10 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_workouts', '0002_alter_workout_instruction_alter_workout_intensity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='intensity',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=50),
        ),
    ]
