# Generated by Django 5.1.7 on 2025-05-06 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('calories', models.PositiveIntegerField(help_text='Calories per serving')),
                ('ingredients', models.TextField(help_text='List ingredients separated by commas')),
                ('instruction', models.TextField(help_text='Step-by-step preparation instructions')),
                ('image_url', models.URLField(blank=True, null=True)),
                ('food_type', models.CharField(choices=[('Vegan', 'Vegan'), ('Vegetarian', 'Vegetarian'), ('Non-Vegetarian', 'Non-Vegetarian')], max_length=20)),
                ('nutrition_type', models.CharField(choices=[('High Carb', 'High Carb'), ('Low Carb', 'Low Carb'), ('High Protein', 'High Protein'), ('Low Protein', 'Low Protein'), ('Balanced', 'Balanced'), ('Very Nutritious', 'Very Nutritious')], max_length=30)),
            ],
        ),
    ]
